import type { PageBlock } from '@/core/types/page-document'

/** Stable document types owned by the optional Dynamic Data plugin. */
export const DATA_LIST_BLOCK_TYPE = 'data-list'
export const DATA_ITEM_BLOCK_TYPE = 'data-item'

export type DataListBlockProps = Record<string, never>
export type DataItemBlockProps = Record<string, never>

/** Query intent persisted on a Data List or Data Item block. */
export interface BlockDataSource {
  collection: string
  sort?: string[]
  limit?: number
  filter?: Record<string, unknown>
}

export interface DataRequirement {
  blockId: string
  kind: 'list' | 'item'
  source: BlockDataSource
}

/** Removes per-row preview suffixes generated by a Data List. */
export function baseBlockId(id: string): string {
  return id.replace(/(?:~\d+)+$/, '')
}

export function isDataBlock(block: Pick<PageBlock, 'type'>): boolean {
  return block.type === DATA_LIST_BLOCK_TYPE || block.type === DATA_ITEM_BLOCK_TYPE
}
