import type { PageDocument } from '@'

export const basicDocument: PageDocument = {
  id: 'demo-page',
  title: 'Demo page',
  version: 1,
  settings: {
    width: 'responsive',
    background: '#eef2f7',
  },
  updatedAt: new Date().toISOString(),
  blocks: [
    {
      id: 'hero-section',
      type: 'section',
      props: {},
      style: {
        paddingTop: '96px',
        paddingBottom: '96px',
        paddingLeft: '24px',
        paddingRight: '24px',
        backgroundColor: '#0f172a',
        color: '#f8fafc',
        textAlign: 'center',
      },
      children: [
        {
          id: 'hero-heading',
          type: 'heading',
          props: { content: 'Library-first page builder', level: 1 },
          style: {
            fontSize: '48px',
            fontWeight: 700,
            lineHeight: '1.1',
            letterSpacing: '-0.02em',
            marginBottom: '16px',
          },
        },
        {
          id: 'hero-text',
          type: 'text',
          props: {
            content: 'Compose pages from configurable primitives with full Webflow-style styling.',
          },
          style: {
            fontSize: '18px',
            color: '#cbd5f5',
            maxWidth: '560px',
            marginLeft: 'auto',
            marginRight: 'auto',
            marginBottom: '24px',
          },
        },
        {
          id: 'hero-cta-row',
          type: 'container',
          props: {},
          style: {
            display: 'flex',
            justifyContent: 'center',
            gap: '12px',
          },
          children: [
            {
              id: 'hero-cta-primary',
              type: 'button',
              props: { label: 'Open docs', href: '#' },
              style: {
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                paddingTop: '8px',
                paddingRight: '16px',
                paddingBottom: '8px',
                paddingLeft: '16px',
                backgroundColor: '#0f766e',
                color: '#ffffff',
                borderTopLeftRadius: '6px',
                borderTopRightRadius: '6px',
                borderBottomRightRadius: '6px',
                borderBottomLeftRadius: '6px',
                fontWeight: 600,
                fontSize: '14px',
                textDecoration: 'none',
              },
            },
            {
              id: 'hero-cta-secondary',
              type: 'button',
              props: { label: 'See examples', href: '#' },
              style: {
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                paddingTop: '8px',
                paddingRight: '16px',
                paddingBottom: '8px',
                paddingLeft: '16px',
                backgroundColor: 'transparent',
                color: '#f8fafc',
                borderTopWidth: '1px',
                borderRightWidth: '1px',
                borderBottomWidth: '1px',
                borderLeftWidth: '1px',
                borderStyle: 'solid',
                borderColor: '#475569',
                borderTopLeftRadius: '6px',
                borderTopRightRadius: '6px',
                borderBottomRightRadius: '6px',
                borderBottomLeftRadius: '6px',
                fontWeight: 600,
                fontSize: '14px',
                textDecoration: 'none',
              },
            },
          ],
        },
      ],
    },
  ],
}
