import type { PageDocument } from '@'

/** Ready-to-edit CSS Anchor Positioning example for the playground. */
export const cssAnchorTemplate: PageDocument = {
  id: 'css-anchor-demo',
  title: 'CSS Anchor',
  version: 1,
  settings: {
    width: 'responsive',
    background: '#f4f1ff',
    style: {
      fontFamily: 'Inter, system-ui, sans-serif',
    },
  },
  updatedAt: new Date().toISOString(),
  blocks: [
    {
      id: 'anchor-stage',
      type: 'section',
      name: 'Anchor stage',
      props: {},
      style: {
        position: 'relative',
        display: 'grid',
        alignItems: 'center',
        justifyItems: 'center',
        minHeight: '520px',
        paddingTop: '48px',
        paddingRight: '48px',
        paddingBottom: '48px',
        paddingLeft: '48px',
        overflow: 'hidden',
      },
      children: [
        {
          id: 'anchor-trigger',
          type: 'button',
          name: 'Anchor trigger',
          props: { label: 'Move me near an edge', href: '#' },
          style: {
            anchorName: '--demo-trigger',
            paddingTop: '12px',
            paddingRight: '18px',
            paddingBottom: '12px',
            paddingLeft: '18px',
            backgroundColor: '#6d28d9',
            color: '#ffffff',
            borderTopLeftRadius: '8px',
            borderTopRightRadius: '8px',
            borderBottomRightRadius: '8px',
            borderBottomLeftRadius: '8px',
            fontWeight: 600,
            textDecoration: 'none',
          },
        },
        {
          id: 'anchor-tooltip',
          type: 'text',
          name: 'Anchored tooltip',
          props: { content: 'I follow the button and flip when space runs out.' },
          style: {
            position: 'absolute',
            positionAnchor: '--demo-trigger',
            positionArea: 'top',
            positionTryFallbacks: 'flip-block',
            width: '220px',
            marginBottom: '10px',
            paddingTop: '10px',
            paddingRight: '12px',
            paddingBottom: '10px',
            paddingLeft: '12px',
            backgroundColor: '#1f1534',
            color: '#ffffff',
            borderTopLeftRadius: '8px',
            borderTopRightRadius: '8px',
            borderBottomRightRadius: '8px',
            borderBottomLeftRadius: '8px',
            fontSize: '13px',
            lineHeight: '1.4',
            textAlign: 'center',
            zIndex: 2,
          },
        },
      ],
    },
  ],
}
